/// <reference types="cypress" />

import login from '../pageObjects/login/login-test';

describe('test', () => {
	it.only('LoginTest', function () {
    const filePath = 'image.jpg';
		cy.visit('http://localhost:5173/');

		cy.fixture('login').then((data) => {
			const ln = new login();
      cy.wait(3000)
			ln.setUserName(data.username);
			ln.setPassword(data.password);
			ln.clickLogin();
		});
    cy.wait(3000)
      cy.get('.app-bar-slot-lead > .flex').click()
      cy.wait(2000)
      cy.contains('Miscellaneous').click()
      cy.wait(2000)
      // eslint-disable-next-line no-useless-escape
      cy.contains('Organizations').click()
      cy.wait(2000)
      cy.get(':nth-child(2) > :nth-child(6) > .btn > .text-lg').click()
      cy.wait(2000)
      cy.get('select[name=type]').select('Clinic')
      cy.wait(2000)
      cy.get('input[name=name]').clear()
      cy.wait(2000)
      cy.get('input[name=name]').type('btrbtr')
      cy.wait(2000)
      cy.get('input[name=contactPhone]').clear()
      cy.wait(2000)
      cy.get('input[name=contactPhone]').type('+91-1234567833')
      cy.wait(2000)
      cy.get('input[name=contactEmail]').clear()
      cy.wait(2000)
      cy.get('input[name=contactEmail]').type('def@gmail.com')
      cy.wait(2000)
      cy.get('textarea[name=about]').clear()
      cy.wait(2000)
      cy.get('textarea[name=about]').type('jymghvxvd')
      cy.wait(2000)
      cy.get('input[name=operationalSince]').clear()
      cy.wait(2000)
      cy.get('input[name=operationalSince]').type('01-Jan-1981')
      cy.wait(2000)
      cy.get('select[name=addressType]').select('Home')
      cy.wait(2000)
      cy.get('input[name=addressLine]').clear()
      cy.wait(2000)
      cy.get('input[name=addressLine]').type('a/p-saswad')
      cy.wait(2000)
      cy.get('input[name=city]').clear()
      cy.wait(2000)
      cy.get('input[name=city]').type('saswad')
      cy.wait(2000)
      cy.get('input[name=district]').clear()
      cy.wait(2000)
      cy.get('input[name=district]').type('pune')
      cy.wait(2000)
      cy.get('select[name=state]').select('Maharashtra')
      cy.wait(2000)
      cy.get('input[name=country]').clear()
      cy.wait(2000)
      cy.get('input[name=country]').type('India')
      cy.wait(2000)
      cy.get('input[name=postalCode]').clear()
      cy.wait(2000)
      cy.get('input[name=postalCode]').type('419301')
      cy.wait(2000)
      cy.get('input[name=fileinput]').attachFile(filePath)
      cy.wait(2000)
      cy.get('input[name=isHealthFacility]').check().should('be.checked')
      cy.wait(2000)
      cy.get('button[type=submit]').click()
      cy.wait(2000)
      cy.contains('Organizations').click()
      cy.wait(2000)
      // cy.contains('→').scrollIntoView()
      // cy.wait(2000)
      // cy.contains('→').click()
      // cy.wait(2000)
      // cy.contains('←').click()
      // cy.wait(2000)
      // cy.get('select').select('20')
      // cy.wait(2000)
      // cy.get('select').select('10')
      // cy.wait(2000)
      // cy.get(':nth-child(1) > .relative > .input').scrollIntoView()
      // cy.wait(2000)
      cy.get('input[name=name]').type('clinic')
      cy.wait(5000)
      cy.get('input[name=name]').clear()
      cy.wait(2000)
      cy.get('input[name=type]').type('orgname')
      cy.wait(5000)
      cy.get('input[name=type]').clear()
    })
	});
 

